name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: testdb
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Wait for MySQL to be ready
        run: |
          for i in `seq 1 30`; do
            nc -z localhost 3306 && echo Success && exit 0
            echo "Waiting for MySQL..."
            sleep 2
          done
          echo "MySQL did not become ready in time" && exit 1
      - name: Build
        run: cd backend && ./mvnw verify -B
        env:
          QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://localhost:3306/almedin
          QUARKUS_DATASOURCE_USERNAME: root
          QUARKUS_DATASOURCE_PASSWORD: 123456
